package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

cc_library(
    name = "glad",
    srcs = ["glad.c"],
    hdrs = ["glad.h"],
    include_prefix = "glad",
    visibility = ["//visibility:public"],
    deps = ["//khrplatform:khr"],
) 