package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

cc_library(
    name = "khr",
    hdrs = ["khrplatform.h"],
    include_prefix = "KHR",
    visibility = ["//visibility:public"],
) 